// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"todo/prisma"
)

type AuthResponse struct {
	User  *prisma.UserModel `json:"user"`
	Token string            `json:"token"`
}

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type NewTodo struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type NewUser struct {
	FirstName string `json:"firstName"`
	LastName  string `json:"lastName"`
	Email     string `json:"email"`
	Password  string `json:"password"`
}
